spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


datahub:
  redis:
    gateway:
      apiService:
        quota:
          key: "datahub:gateway:apiService:quota"
      appkey:
        usedcount:
          key: "datahub:gateway:appkey:usedcount"